version: '3'
services:           
    server-code: 
      restart: always
      container_name: server-code
      build: 
       context: .
       dockerfile: docker-jaeger-example
      depends_on:
         - jaeger     
      ports: 
         - "8080:8080"
      environment: 
         - JAEGER_SERVICE_NAME=hello_service
         - JAEGER_AGENT_HOST=jaeger
         - JAEGER_AGENT_PORT=6831     
         - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:16686
     
      networks:
        - backbonevalue
           
    jaeger: 
      image: jaegertracing/all-in-one:latest
      container_name: opentracing
      ports: 
          - "5775:5775/udp"
          - "6831:6831/udp"
          - "6832:6832/udp"
          - "5778:5778"
          - "16686:16686"
          - "14268:14268"
          - "9411:9411"
      
      networks:
        - backbonevalue
       
networks:
  backbonevalue: 
   driver: bridge          